-- public.auth_group definition

-- Drop table

-- DROP TABLE auth_group;

CREATE TABLE auth_group ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, "name" varchar(150) NOT NULL, CONSTRAINT auth_group_name_key UNIQUE (name), CONSTRAINT auth_group_pkey PRIMARY KEY (id));
CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


-- public.auth_user definition

-- Drop table

-- DROP TABLE auth_user;

CREATE TABLE auth_user ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, "password" varchar(128) NOT NULL, last_login timestamptz NULL, is_superuser bool NOT NULL, username varchar(150) NOT NULL, first_name varchar(150) NOT NULL, last_name varchar(150) NOT NULL, email varchar(254) NOT NULL, is_staff bool NOT NULL, is_active bool NOT NULL, date_joined timestamptz NOT NULL, CONSTRAINT auth_user_pkey PRIMARY KEY (id), CONSTRAINT auth_user_username_key UNIQUE (username));
CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


-- public.django_content_type definition

-- Drop table

-- DROP TABLE django_content_type;

CREATE TABLE django_content_type ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, app_label varchar(100) NOT NULL, model varchar(100) NOT NULL, CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model), CONSTRAINT django_content_type_pkey PRIMARY KEY (id));


-- public.django_migrations definition

-- Drop table

-- DROP TABLE django_migrations;

CREATE TABLE django_migrations ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, app varchar(255) NOT NULL, "name" varchar(255) NOT NULL, applied timestamptz NOT NULL, CONSTRAINT django_migrations_pkey PRIMARY KEY (id));


-- public.django_session definition

-- Drop table

-- DROP TABLE django_session;

CREATE TABLE django_session ( session_key varchar(40) NOT NULL, session_data text NOT NULL, expire_date timestamptz NOT NULL, CONSTRAINT django_session_pkey PRIMARY KEY (session_key));
CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


-- public.ganjoor_poet definition

-- Drop table

-- DROP TABLE ganjoor_poet;

CREATE TABLE ganjoor_poet ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "name" varchar(255) NOT NULL, description text NOT NULL, century varchar(20) NOT NULL, image varchar(100) NULL, image_slug varchar(255) NULL, CONSTRAINT ganjoor_poet_pkey PRIMARY KEY (id));
CREATE INDEX ganjoor_poet_century_7cb0580d ON public.ganjoor_poet USING btree (century);
CREATE INDEX ganjoor_poet_century_7cb0580d_like ON public.ganjoor_poet USING btree (century varchar_pattern_ops);
CREATE INDEX ganjoor_poet_name_5351f441 ON public.ganjoor_poet USING btree (name);
CREATE INDEX ganjoor_poet_name_5351f441_like ON public.ganjoor_poet USING btree (name varchar_pattern_ops);


-- public.tmp_poets definition

-- Drop table

-- DROP TABLE tmp_poets;

CREATE TABLE tmp_poets ( "name" varchar(255) NOT NULL, image_slug varchar(255) NULL);


-- public.auth_permission definition

-- Drop table

-- DROP TABLE auth_permission;

CREATE TABLE auth_permission ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, "name" varchar(255) NOT NULL, content_type_id int4 NOT NULL, codename varchar(100) NOT NULL, CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename), CONSTRAINT auth_permission_pkey PRIMARY KEY (id), CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


-- public.auth_user_groups definition

-- Drop table

-- DROP TABLE auth_user_groups;

CREATE TABLE auth_user_groups ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, user_id int4 NOT NULL, group_id int4 NOT NULL, CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id), CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id), CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED, CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);
CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


-- public.auth_user_user_permissions definition

-- Drop table

-- DROP TABLE auth_user_user_permissions;

CREATE TABLE auth_user_user_permissions ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, user_id int4 NOT NULL, permission_id int4 NOT NULL, CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id), CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id), CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED, CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);
CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


-- public.core_usersetting definition

-- Drop table

-- DROP TABLE core_usersetting;

CREATE TABLE core_usersetting ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, view_mode varchar(50) NOT NULL, font_size float8 NOT NULL, show_line_numbers bool NOT NULL, last_highlight varchar(255) NULL, browse_button_visible bool NOT NULL, comments_button_visible bool NOT NULL, copy_button_visible bool NOT NULL, print_button_visible bool NOT NULL, home_button_visible bool NOT NULL, random_button_visible bool NOT NULL, editor_button_visible bool NOT NULL, download_button_visible bool NOT NULL, user_id int4 NOT NULL, CONSTRAINT core_usersetting_pkey PRIMARY KEY (id), CONSTRAINT core_usersetting_user_id_key UNIQUE (user_id), CONSTRAINT core_usersetting_user_id_7e930b39_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED);


-- public.django_admin_log definition

-- Drop table

-- DROP TABLE django_admin_log;

CREATE TABLE django_admin_log ( id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL, action_time timestamptz NOT NULL, object_id text NULL, object_repr varchar(200) NOT NULL, action_flag int2 NOT NULL, change_message text NOT NULL, content_type_id int4 NULL, user_id int4 NOT NULL, CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0)), CONSTRAINT django_admin_log_pkey PRIMARY KEY (id), CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED, CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


-- public.ganjoor_category definition

-- Drop table

-- DROP TABLE ganjoor_category;

CREATE TABLE ganjoor_category ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, title varchar(255) NOT NULL, url varchar(255) NULL, parent_id int8 NULL, poet_id int8 NOT NULL, CONSTRAINT ganjoor_category_pkey PRIMARY KEY (id), CONSTRAINT ganjoor_category_parent_id_cada1e20_fk_ganjoor_category_id FOREIGN KEY (parent_id) REFERENCES ganjoor_category(id) DEFERRABLE INITIALLY DEFERRED, CONSTRAINT ganjoor_category_poet_id_505e0d6c_fk_ganjoor_poet_id FOREIGN KEY (poet_id) REFERENCES ganjoor_poet(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX ganjoor_category_parent_id_cada1e20 ON public.ganjoor_category USING btree (parent_id);
CREATE INDEX ganjoor_category_poet_id_505e0d6c ON public.ganjoor_category USING btree (poet_id);
CREATE INDEX ganjoor_category_title_d0599066 ON public.ganjoor_category USING btree (title);
CREATE INDEX ganjoor_category_title_d0599066_like ON public.ganjoor_category USING btree (title varchar_pattern_ops);


-- public.ganjoor_poem definition

-- Drop table

-- DROP TABLE ganjoor_poem;

CREATE TABLE ganjoor_poem ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, title varchar(255) NOT NULL, url varchar(255) NOT NULL, category_id int8 NOT NULL, CONSTRAINT ganjoor_poem_pkey PRIMARY KEY (id), CONSTRAINT ganjoor_poem_category_id_ee431106_fk_ganjoor_category_id FOREIGN KEY (category_id) REFERENCES ganjoor_category(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX ganjoor_poem_category_id_ee431106 ON public.ganjoor_poem USING btree (category_id);
CREATE INDEX ganjoor_poem_title_5ed501e6 ON public.ganjoor_poem USING btree (title);
CREATE INDEX ganjoor_poem_title_5ed501e6_like ON public.ganjoor_poem USING btree (title varchar_pattern_ops);
CREATE INDEX ganjoor_poem_url_6287462d ON public.ganjoor_poem USING btree (url);
CREATE INDEX ganjoor_poem_url_6287462d_like ON public.ganjoor_poem USING btree (url varchar_pattern_ops);


-- public.ganjoor_poem_audio definition

-- Drop table

-- DROP TABLE ganjoor_poem_audio;

CREATE TABLE ganjoor_poem_audio ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, file varchar(100) NOT NULL, description text NULL, download_url varchar(500) NOT NULL, is_direct bool NOT NULL, sync_guid varchar(255) NOT NULL, file_checksum varchar(255) NOT NULL, is_uploaded bool NOT NULL, poem_id int8 NOT NULL, CONSTRAINT ganjoor_poem_audio_pkey PRIMARY KEY (id), CONSTRAINT ganjoor_poem_audio_poem_id_402b2aac_fk_ganjoor_poem_id FOREIGN KEY (poem_id) REFERENCES ganjoor_poem(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX ganjoor_poem_audio_poem_id_402b2aac ON public.ganjoor_poem_audio USING btree (poem_id);
CREATE INDEX ganjoor_poem_audio_sync_guid_6a77ee82 ON public.ganjoor_poem_audio USING btree (sync_guid);
CREATE INDEX ganjoor_poem_audio_sync_guid_6a77ee82_like ON public.ganjoor_poem_audio USING btree (sync_guid varchar_pattern_ops);


-- public.ganjoor_verse definition

-- Drop table

-- DROP TABLE ganjoor_verse;

CREATE TABLE ganjoor_verse ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, "order" int4 NOT NULL, "text" text NOT NULL, poem_id int8 NOT NULL, "position" int2 NOT NULL, CONSTRAINT ganjoor_verse_order_check CHECK (("order" >= 0)), CONSTRAINT ganjoor_verse_pkey PRIMARY KEY (id), CONSTRAINT unique_verse_per_poem UNIQUE ("order", poem_id), CONSTRAINT ganjoor_verse_poem_id_29b1e696_fk_ganjoor_poem_id FOREIGN KEY (poem_id) REFERENCES ganjoor_poem(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX ganjoor_verse_order_602ab1e0 ON public.ganjoor_verse USING btree ("order");
CREATE INDEX ganjoor_verse_poem_id_29b1e696 ON public.ganjoor_verse USING btree (poem_id);


-- public.auth_group_permissions definition

-- Drop table

-- DROP TABLE auth_group_permissions;

CREATE TABLE auth_group_permissions ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, group_id int4 NOT NULL, permission_id int4 NOT NULL, CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id), CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id), CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED, CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


-- public.ganjoor_audio_sync definition

-- Drop table

-- DROP TABLE ganjoor_audio_sync;

CREATE TABLE ganjoor_audio_sync ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, verse_order int4 NOT NULL, millisec int4 NOT NULL, poem_id int8 NOT NULL, audio_id int8 NOT NULL, CONSTRAINT ganjoor_audio_sync_millisec_check CHECK ((millisec >= 0)), CONSTRAINT ganjoor_audio_sync_pkey PRIMARY KEY (id), CONSTRAINT ganjoor_audio_sync_verse_order_check CHECK ((verse_order >= 0)), CONSTRAINT ganjoor_audio_sync_audio_id_8695df4c_fk_ganjoor_poem_audio_id FOREIGN KEY (audio_id) REFERENCES ganjoor_poem_audio(id) DEFERRABLE INITIALLY DEFERRED, CONSTRAINT ganjoor_audio_sync_poem_id_6ff21f3b_fk_ganjoor_poem_id FOREIGN KEY (poem_id) REFERENCES ganjoor_poem(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX ganjoor_audio_sync_audio_id_8695df4c ON public.ganjoor_audio_sync USING btree (audio_id);
CREATE INDEX ganjoor_audio_sync_poem_id_6ff21f3b ON public.ganjoor_audio_sync USING btree (poem_id);


-- public.ganjoor_favorite definition

-- Drop table

-- DROP TABLE ganjoor_favorite;

CREATE TABLE ganjoor_favorite ( id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL, created_at timestamptz NOT NULL, user_id int4 NOT NULL, poem_id int8 NOT NULL, verse_id int8 NOT NULL, CONSTRAINT ganjoor_favorite_pkey PRIMARY KEY (id), CONSTRAINT unique_user_poem_verse_fav UNIQUE (user_id, poem_id, verse_id), CONSTRAINT ganjoor_favorite_poem_id_7b1e248f_fk_ganjoor_poem_id FOREIGN KEY (poem_id) REFERENCES ganjoor_poem(id) DEFERRABLE INITIALLY DEFERRED, CONSTRAINT ganjoor_favorite_user_id_eaea4222_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED, CONSTRAINT ganjoor_favorite_verse_id_957fb81f_fk_ganjoor_verse_id FOREIGN KEY (verse_id) REFERENCES ganjoor_verse(id) DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX ganjoor_favorite_poem_id_7b1e248f ON public.ganjoor_favorite USING btree (poem_id);
CREATE INDEX ganjoor_favorite_user_id_eaea4222 ON public.ganjoor_favorite USING btree (user_id);
CREATE INDEX ganjoor_favorite_verse_id_957fb81f ON public.ganjoor_favorite USING btree (verse_id);